/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Chess_GUI.java
 *
 * Created on Mar 17, 2009, 4:32:39 PM
 */

/**
 *
 * @author Hai
 *
 */
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;
import java.awt.event.*;
import java.text.DecimalFormat;
import java.io.*;
import javax.swing.filechooser.FileNameExtensionFilter;

public class Chess_GUI extends javax.swing.JFrame {

    /** Creates new form Chess_GUI */
    public Chess_GUI() {
        initComponents();
        setTitle("Co Vua");
        setLocation(150,100);
        skin=1;
        mychess = new Chess();   // khoi tao tro choi co vua
        mychess.setSkin(skin);
        jFileChooser1= new  JFileChooser("Save");   //khoi tao cua so save,load
        jFileChooser1.setFileFilter(new FileNameExtensionFilter("chessFile(.chess)","chess"));
        for(int i=0;i<8;i++)
           for(int j=0;j<8;j++)
           {
               button[i][j] = new JButton();
               button[i][j].setBorder(null);
               // tao mau cho cac o
               if((i+j)%2==1)button[i][j].setBackground(new Color(0,204,204));
                 else button[i][j].setBackground(Color.WHITE);
               jPanel1.add(button[i][j]);
               
               // xu li hanh dong click vao 1 o
               button[i][j].addActionListener( new ActionListener(){
                     public void actionPerformed(ActionEvent e){
                            for(int i=0;i<8;i++)
                                 for(int j=0;j<8;j++)
                                   if(button[i][j]==e.getSource()){
                                         mychess.receiveMouseClicked(mychess.getBoard(i,j));
                                         break;
                                   }
                            display();     //hien thi lai hinh anh ban co
                            if(mychess.checkFinish())  // kiem tra xem van co da ket thuc chua
                            {
                                  time.stop();
                                  if(mychess.getWin()==0)
                                       JOptionPane.showMessageDialog(null, "   Black Win !" , "Game Over", 1);
                                  else JOptionPane.showMessageDialog(null, "   White Win !" , "Game Over", 1);
                                  mychess =new Chess();  //tao van' choi moi
                                  display();
                                  timePlay();
                            } 
                     }
                    });
           }
        display(); // hien thi hinh anh ban co
        timePlay();  // hien thi thoi gian choi
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton10 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jFileChooser1.setCurrentDirectory(new java.io.File("H:\\Save"));

        jButton7.setText("jButton7");
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton7)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jButton7)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.jpg"))); // NOI18N
        jButton1.setText("Player 1");
        jPanel2.add(jButton1);
        jButton1.setBounds(0, 90, 130, 160);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.jpg"))); // NOI18N
        jButton2.setText("Player 2");
        jPanel2.add(jButton2);
        jButton2.setBounds(0, 310, 130, 160);

        jButton8.setFont(new java.awt.Font("Arial", 1, 18));
        jButton8.setText("00 : 00 : 00");
        jPanel2.add(jButton8);
        jButton8.setBounds(0, 0, 130, 40);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 16));
        jButton9.setText("Turn");
        jPanel2.add(jButton9);
        jButton9.setBounds(0, 40, 130, 50);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 252, 130, 10);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 16));
        jButton10.setText("Wait !");
        jPanel2.add(jButton10);
        jButton10.setBounds(0, 250, 130, 60);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 480));
        jPanel1.setLayout(new java.awt.GridLayout(8, 8));

        jPanel3.setLayout(new java.awt.GridLayout(1, 5));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newgame.png"))); // NOI18N
        jButton3.setToolTipText("New Game");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/savegame.png"))); // NOI18N
        jButton4.setToolTipText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loadgame.png"))); // NOI18N
        jButton5.setToolTipText("Load");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/undo.png"))); // NOI18N
        jButton6.setToolTipText("Undo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);

        jMenu1.setMnemonic('g');
        jMenu1.setText("Game");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setMnemonic('n');
        jMenuItem1.setText("New game");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setMnemonic('U');
        jMenuItem6.setText("Undo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setMnemonic('s');
        jMenuItem2.setText("Save game");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setMnemonic('L');
        jMenuItem3.setText("Load game");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setMnemonic('E');
        jMenuItem8.setText("Exit");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu3.setMnemonic('o');
        jMenu3.setText("Options");

        jRadioButtonMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        buttonGroup1.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.setMnemonic('P');
        jRadioButtonMenuItem1.setText("Player vs Player");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        buttonGroup1.add(jRadioButtonMenuItem2);
        jRadioButtonMenuItem2.setMnemonic('C');
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Computer vs Player");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu2.setMnemonic('k');
        jMenu2.setText("Skins");

        buttonGroup2.add(jRadioButtonMenuItem3);
        jRadioButtonMenuItem3.setMnemonic('1');
        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("Skin 1");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem3);

        buttonGroup2.add(jRadioButtonMenuItem4);
        jRadioButtonMenuItem4.setMnemonic('2');
        jRadioButtonMenuItem4.setText("Skin 2");
        jRadioButtonMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem4);

        buttonGroup2.add(jRadioButtonMenuItem5);
        jRadioButtonMenuItem5.setMnemonic('3');
        jRadioButtonMenuItem5.setText("Skin 3");
        jRadioButtonMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu4.setMnemonic('H');
        jMenu4.setText("Help");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem4.setMnemonic('e');
        jMenuItem4.setText("Help me");
        jMenu4.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem5.setMnemonic('A');
        jMenuItem5.setText("About");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JOptionPane.showMessageDialog(null, "Authors:" +
                "\n Bùi Ngọc Hải  \n Lê Xuân Thành", "About", 1);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    //hanh dong khi click exit
    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    // click menu item new game
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        mychess= new Chess();
        mychess.setSkin(skin);
        time.stop();
        display();        
        timePlay();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // click menu item save game
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jFileChooser1.showSaveDialog(null);
        try {
            mychess.save(jFileChooser1.getSelectedFile().getPath());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Chess_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        mychess.setSkin(skin);
        display();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // click menu item load game
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jFileChooser1.showSaveDialog(null);
        try {
            mychess.load(jFileChooser1.getSelectedFile().getPath());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Chess_GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Chess_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        display();
        mychess.setSkin(skin);
        display();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    // click menu item undo
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        mychess.undo();
        display();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    // chon che do nguoi choi voi nguoi
    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        mychess= new Chess();
        mychess.setSkin(skin);
        mychess.setMode(1);
        time.stop();
        display();
        timePlay();
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    // chon che do nguoi choi voi may
    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        mychess= new Chess();
        mychess.setSkin(skin);
        mychess.setMode(2);
        time.stop();
        display();
        timePlay();
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    //click button new game
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mychess= new Chess();
        mychess.setSkin(skin);
        time.stop();
        display();
        timePlay();
    }//GEN-LAST:event_jButton3ActionPerformed

    //click button save game
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jFileChooser1.showSaveDialog(null);
        try {
            mychess.save(jFileChooser1.getSelectedFile().getPath());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Chess_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        mychess.setSkin(skin);
        display();
    }//GEN-LAST:event_jButton4ActionPerformed

    //click button load game
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jFileChooser1.showOpenDialog(null);
        try {
            mychess.load(jFileChooser1.getSelectedFile().getPath());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Chess_GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Chess_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        mychess.setSkin(skin);
        display();
    }//GEN-LAST:event_jButton5ActionPerformed

    //click button undo
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         mychess.undo();
        display();
    }//GEN-LAST:event_jButton6ActionPerformed
    //chon skin 1
    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        skin=1;
        mychess.setSkin(skin);
        // the hien mau cua o ban co
        for(int i=0;i<8;i++)
           for(int j=0;j<8;j++)
              if((i+j)%2==1)button[i][j].setBackground(new Color(0,204,204));
                 else button[i][j].setBackground(Color.WHITE);

        jButton1.setIcon(new ImageIcon("images/1.jpg"));
        jButton2.setIcon(new ImageIcon("images/2.jpg"));
        display();
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed
    //chon skin 2
    private void jRadioButtonMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem4ActionPerformed
        skin=2;
        mychess.setSkin(skin);
        // the hien mau cua o ban co
        for(int i=0;i<8;i++)
           for(int j=0;j<8;j++)
              if((i+j)%2==1)button[i][j].setBackground(new Color(51,180,255));
                 else button[i][j].setBackground(Color.WHITE);

        jButton1.setIcon(new ImageIcon("images/3.jpg"));
        jButton2.setIcon(new ImageIcon("images/4.jpg"));
        display();
    }//GEN-LAST:event_jRadioButtonMenuItem4ActionPerformed
    //chon skin 3
    private void jRadioButtonMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem5ActionPerformed
        skin=3;
        mychess.setSkin(skin);
        // the hien mau cua o ban co
        for(int i=0;i<8;i++)
           for(int j=0;j<8;j++)
              if((i+j)%2==1)button[i][j].setBackground(Color.DARK_GRAY);
                 else button[i][j].setBackground(Color.WHITE);

        jButton1.setIcon(new ImageIcon("images/5.jpg"));
        jButton2.setIcon(new ImageIcon("images/6.jpg"));
        display();
    }//GEN-LAST:event_jRadioButtonMenuItem5ActionPerformed
    // hien thi hinh anh ban co
    public void display(){
        Cell tmpBoard[][] = new Cell[8][8];
        for(int i=0;i<8;i++)
           for(int j=0;j<8;j++)
           {
               button[i][j].setIcon(null);
               if(mychess.getBoard(i,j).getAChessman()!=null)
                   if(mychess.getBoard(i,j).getAChessman().getDied()==false) //quan co con song
                       button[i][j].setIcon(
                             mychess.getBoard(i,j).getAChessman().getAnIcon());  //hien thi hinh anh quan co
               
		       button[i][j].setBorder(null);
               tmpBoard[i][j]=mychess.getBoard(i,j);
           }
        if(mychess.getTurn()==false) //nguoi choi 0 duoc di
         {
               Cell tmp=mychess.getPlayer(0).getSelected();
               if(tmp!=null)
                    button[tmp.getRow()][tmp.getColumn()].setBorder(
                             new LineBorder(new Color(69,76,113),3));   //danh dau o duoc click
               // danh dau cac o co the di den
               if(tmp!=null)
                  for(int i=0;i<8;i++)
                      for(int j=0;j<8;j++)
                          if(tmp.getAChessman().move(tmp, mychess.getBoard(i,j), tmpBoard))
                              button[i][j].setBorder(new LineBorder(Color.BLUE,1));

               jButton9.setText("Turn");
               jButton10.setText("Wait !");
               jButton10.setForeground(Color.BLUE);
         }
         else     //nguoi choi 1 duoc di
         {
               Cell tmp=mychess.getPlayer(1).getSelected();
               if(tmp!=null)
                   button[tmp.getRow()][tmp.getColumn()].setBorder(
                        new LineBorder(new Color(69,76,113),3));  //danh dau o duoc click
               // danh dau cac o co the di den
               if(tmp!=null)
                   for(int i=0;i<8;i++)
                       for(int j=0;j<8;j++)
                          if(tmp.getAChessman().move(tmp, mychess.getBoard(i,j), tmpBoard))
                               button[i][j].setBorder(new LineBorder(Color.BLUE,1));

               jButton9.setText("Wait !");
               jButton9.setForeground(Color.BLUE);
               jButton10.setText("Turn");
         }
    }

    // hien thi thoi gian choi
    public void timePlay(){
        final DecimalFormat df=new DecimalFormat("00");
        hour=minute=second=0;
        jButton8.setText(df.format(hour)+" : "
                      +df.format(minute)+" : "+df.format(second) );
        //----
    	time=new Timer(1000,new ActionListener(){
        public void actionPerformed(ActionEvent e){
              second++;
	          if(second==60){
				minute++;
	            second=0;
			  }
	          if(minute==60){
	          	hour++;
	            minute=0;
              }
	          jButton8.setText(df.format(hour)+" : "
                      +df.format(minute)+" : "+df.format(second) );
              // doi mau chu~ ,lam chu~ nhap nhay
              if(second%2==0){
                  if(jButton9.getText().compareTo("Turn") == 0)
                      jButton9.setForeground(Color.BLUE);
                  else jButton10.setForeground(Color.BLUE);
              }
              else {
                  if(jButton9.getText().compareTo("Turn") == 0)
                      jButton9.setForeground(Color.MAGENTA);
                  else jButton10.setForeground(Color.MAGENTA);
              }
	      }
    	});
        //------
        time.start();
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chess_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    private JButton button[][] = new JButton[8][8];
    Timer time;
    int second;
    int minute;
    int hour;
    int skin; // kieu skin cua tro choi
    Chess mychess;
}
